### ISSUE TITLE
About feature_size=1536

### ISSUE THREAD

**Issue by becauseofAI** [romulus0914/MixNet-Pytorch#1]
What's mean of feature_size and why the value is 1536?

**Comment by romulus0914** [comment]
Just like the “stem convolution” before any blocks of convolution, it’s a convention to add a 1x1 convolution to expand the channels. Therefore, “feature_size” means the final channels of convolution before a linear classifier. However, normally, it should be 1280 instead of 1536, but it is a hyper-parameter set by authors in the official released code.
